project_id = "ploqujuhpwutpcibedbr"

[functions.create-admin-user]
verify_jwt = false

[functions.import-users]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.patient-data-report]
verify_jwt = false

[functions.activate-communicare-manual]
verify_jwt = false
